global_frame: map
robot_base_frame: base_link

update_frequency: 1.0
publish_frequency: 0.5
transform_tolerance: 0.5
static_map: true

inflater:
  enabled: true
  # robot_radius: 0.01
  inflation_radius: 0.2
  cost_scaling_factor: 20

plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
