global_frame: odom

update_frequency: 5.0
publish_frequency: 2.0

rolling_window: true

# size of costmap is specified in robot folder

# plugins for local costmap are in robot folder


inflater:
  enabled: true
  inflation_radius: 0.2
  cost_scaling_factor: 20

plugins:
  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}